Parameters uniformization in doc
anlsys/aml pull request #179
Opened 2021-04-27 20:30 UTC by fmonna

Uniformization of parameter presentation in the documentation.
- put all parameters to @param[in] name format.
- set all function descriptions starting with a verb to infinitive
- set all the parameters descriptions to a start without capitalization

2021-04-27 21:04 UTC, perarnau commented
Nice! I can see a few errors here and there. And clang-format made a mess of course. I'll comment on the errors as I go through the doc.

2021-04-27 21:24 UTC, perarnau requested changes
Quite nice, I didn't realize we had so many missing metadata in this header. Thanks.
As a general rule, the generic api and the implementation should match. It seems to be the case here for everything. The fprintf one is the same mistake repeated across the file, that's all.

I saw a couple of [out] that could be argued against, but let's leave them as they are for now.

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> + * @param[in] argv: pointer to the main()'s argv argument; contents can get
```suggestion
 * @param[inout] argv: pointer to the main()'s argv argument; contents can get
```
Same for the other.

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[out] stream: the stream to print to
```suggestion
	 * @param[in] stream: the stream to print to
```
That's actually an `in`, even though we "write" into it

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> + * @param[out] stream: the stream to print on
```suggestion
 * @param[in] stream: the stream to print on
```
Same as the function pointer definition. As a rule, there shouldn't be any difference between the generic API and the implementation prototypes, outside of very specific reasons.

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[out] stream: the stream to print to
```suggestion
	 * @param[in] stream: the stream to print to
```
Idem

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> + * @param[out] stream: the stream to print on
```suggestion
 * @param[in] stream: the stream to print on
```
Idem

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> + * @return -AML_SUCCESS if copy succeeded.
Typo ?

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[out] stream: the stream to print to
```suggestion
	 * @param[in] stream: the stream to print to
```
Idem

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> + * @param[out] stream: the stream to print on
```suggestion
 * @param[in] stream: the stream to print on
```
Idem

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[in, out] req: the request handle to manage termination
I think we can keep it just out

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[in] req: the request handle to manage termination of the
```suggestion
	 * @param[inout] req: the request handle to manage termination of the
```
If I remember correctly, this one gets set to NULL on exit.

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[in] req: the request handle to manage termination of the
Same as destroy

2021-04-27 21:24 UTC, perarnau commented on include/aml.h
> +	 * @param[out] stream: the stream to print to
The usual

2021-04-28 19:53 UTC, fmonna commented on include/aml.h
> +	 * @param[in, out] req: the request handle to manage termination
Ok I'll leave the inout for the dma and switch to out for req

2021-04-28 20:15 UTC, perarnau approved these changes

2021-04-28 20:20 UTC, perarnau requested changes

2021-04-28 20:20 UTC, perarnau commented on include/aml.h
> + * @param[in] argc: pointer to the main()'s argc argument; contents can get
```suggestion
 * @param[inout] argc: pointer to the main()'s argc argument; contents can get
```

2021-04-28 20:20 UTC, perarnau approved these changes

2021-04-28 20:29 UTC, merged