[feature] multiplexing dmas
anlsys/aml pull request #233
Opened 2023-05-02 14:41 UTC by perarnau

2023-05-02 16:07 UTC, iskra-anl requested changes
There are some iffy things in one of the files but I'm not sure if that file is included in this PR on purpose?

2023-05-02 18:12 UTC, perarnau commented on tests/dma/test-aml-dma-omp.c
it's not an actual test, more of a benchmark. I could add it to the tests when ze is active though

2023-05-04 14:53 UTC, iskra-anl approved these changes

2023-05-04 14:57 UTC, iskra-anl approved these changes

2023-05-08 15:38 UTC, merged